const STORAGE='human-matrix.profiles.v1';
const DEFAULT=[{id:crypto.randomUUID(),name:'Алексей',birth:'1989-03-26',time:'',place:'Сестрорецк, Ленинград',tz:'Europe/Moscow',accuracy:'Время неизвестно',notes:[]}];
const state={mode:'person',active:0,editing:null,pairA:0,pairB:1,people:load()};
const tabs=[['person','Человек'],['pair','Пара'],['team','Команда 3–5'],['systems','Системы'],['observations','Наблюдения']];
function load(){try{const v=JSON.parse(localStorage.getItem(STORAGE)||'null');return Array.isArray(v)&&v.length?v:DEFAULT}catch{return DEFAULT}}
function persist(){localStorage.setItem(STORAGE,JSON.stringify(state.people))}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmtDate(v){if(!v)return 'дата не указана';const[y,m,d]=v.split('-');return `${d}.${m}.${y}`}
function active(){return state.people[state.active]}
function calcFor(p){if(!p?.birth||!p?.time||!p?.tz)return{ready:false,reason:'Для расчёта нужны дата, время и IANA-часовой пояс.'};try{return{ready:true,...HumanMatrixHD.calculate({date:p.birth,time:p.time,tz:p.tz})}}catch(e){return{ready:false,reason:e?.message||String(e)}}}
function renderPeople(){const el=document.getElementById('persons');el.innerHTML=state.people.map((p,i)=>`<div class="person ${i===state.active?'active':''}" onclick="state.active=${i};render()"><div class="row"><div class="avatar">${esc((p.name||'?')[0])}</div><div><b>${esc(p.name)}</b><small>${fmtDate(p.birth)} · ${esc(p.place||'место не указано')}</small></div></div><div class="row"><button class="btn" title="Редактировать" onclick="event.stopPropagation();openEdit(${i})">✎</button><button class="btn" title="Удалить" onclick="event.stopPropagation();removePerson(${i})">×</button></div></div>`).join('');document.getElementById('addBtn').disabled=state.people.length>=5}
function renderTabs(){document.getElementById('tabs').innerHTML=tabs.map(([k,n])=>`<div class="tab ${state.mode===k?'active':''}" onclick="state.mode='${k}';renderContent()">${n}</div>`).join('')}
function centerSvg(hd){const pos={head:[180,28],ajna:[180,82],throat:[180,145],g:[180,218],heart:[250,225],sacral:[180,300],solarplexus:[280,300],spleen:[80,300],root:[180,382]};const defined=new Set(hd.definedCenters);const lines=hd.channels.map(ch=>{const a=pos[ch.centers[0]],b=pos[ch.centers[1]];return`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" stroke="#8ab4ff" stroke-width="5" stroke-linecap="round" opacity=".75"/>`}).join('');const nodes=Object.entries(pos).map(([k,[x,y]])=>`<g><circle cx="${x}" cy="${y}" r="23" fill="${defined.has(k)?'#8ab4ff':'#111a2d'}" stroke="${defined.has(k)?'#cfe0ff':'#42506d'}" stroke-width="2"/><text x="${x}" y="${y+4}" text-anchor="middle" font-size="10" fill="${defined.has(k)?'#07101f':'#c7d0e3'}">${esc(HumanMatrixHD.CENTER_LABELS[k])}</text></g>`).join('');return`<div class="bodygraph"><div class="label">Схема определённости центров</div><svg viewBox="0 0 360 420" role="img" aria-label="Схема центров Human Design">${lines}${nodes}</svg><div class="muted" style="font-size:12px">Функциональная схема центров и каналов, не копия фирменного BodyGraph.</div></div>`}
function precisionLabel(c){return c?.precision?.gate==='reliable'?'ворота/линии: надёжно':'точность требует проверки'}
function hdSummary(c){const h=c.hd;return`<div class="stats"><div class="stat"><span class="label">Тип</span><strong>${esc(h.type)}</strong></div><div class="stat"><span class="label">Профиль</span><strong>${esc(h.profile)}</strong></div><div class="stat"><span class="label">Авторитет</span><strong>${esc(h.authority)}</strong></div><div class="stat"><span class="label">Стратегия</span><strong style="font-size:15px">${esc(h.strategy)}</strong></div></div>`}
function channelCards(h){const channels=h.channels.length?h.channels.map(ch=>`<div class="channel"><b>${ch.gates.join('–')} · ${esc(ch.name||'')}</b><span class="muted">${esc(ch.centers.map(c=>HumanMatrixHD.CENTER_LABELS[c]).join(' ↔ '))}</span></div>`).join(''):'<span class="muted">Нет полностью определённых каналов.</span>';return`<div class="card"><b>Определённые каналы · ${h.channels.length}</b><div class="channelList">${channels}</div></div><div class="card"><b>Активированные ворота · ${h.gates.length}</b><div class="gateList">${h.gates.map(g=>`<span class="gate">${g}</span>`).join('')}</div></div>`}
function hypothesisCards(h){
 const typeMap={
  'Manifestor':'Эксперимент: перед значимым самостоятельным действием заранее информировать тех, кого оно затронет, и наблюдать, уменьшается ли сопротивление.',
  'Generator':'Эксперимент: перед обязательством замечать, есть ли телесный отклик на конкретный вариант, а не только мысленное «надо».',
  'Manifesting Generator':'Эксперимент: сначала проверить отклик, затем быстро тестировать действие и информировать затронутых людей при смене направления.',
  'Projector':'Эксперимент: различать ситуации, где ваш взгляд действительно запрошен и признан, и где вы пытаетесь доказать полезность без приглашения.',
  'Reflector':'Эксперимент: для крупных решений давать себе больше времени и сравнивать ощущения в разных людях и средах.'
 };
 const authMap={
  'Emotional':'Не считать эмоциональный пик окончательной ясностью; возвращаться к важному решению после прохождения волны.',
  'Sacral':'Проверять непосредственный телесный отклик на конкретные «да/нет» варианты.',
  'Splenic':'Замечать тихую мгновенную интуитивную реакцию до того, как её перекроет анализ.',
  'Ego':'Проверять: «Я действительно этого хочу и готов это обещать?» — особенно перед обязательствами.',
  'Self-Projected':'Проговаривать решение вслух и слышать собственное направление в речи.',
  'Mental / Environmental':'Использовать людей как звуковую доску, но обращать особое внимание на качество среды, а не на чужой совет.',
  'Lunar':'Для крупных решений использовать продолжительный цикл наблюдения, а не искать мгновенную определённость.'
 };
 const line={1:'исследование и надёжная основа',2:'естественный талант и потребность в уединении',3:'обучение через пробу и ошибку',4:'влияние через устойчивые связи',5:'практические решения и сильные проекции окружающих',6:'дистанция, наблюдение и созревание ролевого примера'};
 const [a,b]=String(h.profile||'').split('/').map(Number);
 return `<div class="cards"><div class="card"><b>Гипотеза по типу</b><span class="muted">${esc(typeMap[h.type]||'Наблюдать, какие условия помогают действовать устойчиво.')}</span></div><div class="card"><b>Гипотеза по авторитету</b><span class="muted">${esc(authMap[h.authority]||'Использовать как тему для наблюдения, а не как правило.')}</span></div><div class="card"><b>Профиль ${esc(h.profile)}</b><span class="muted">Сочетание тем: ${esc(line[a]||'—')} + ${esc(line[b]||'—')}.</span></div><div class="card"><b>Как проверять</b><span class="muted">Запишите ожидание заранее → попробуйте в реальной ситуации → зафиксируйте результат во вкладке «Наблюдения».</span></div></div>`
}
function personView(){const p=active();if(!p)return'<div class="notice">Добавьте участника.</div>';const c=calcFor(p);if(!c.ready)return`<div class="heroCard"><div class="label">Профиль участника</div><h2>${esc(p.name)}</h2><div class="chips"><span class="chip">Human Design · нужны исходные данные</span><span class="chip">${esc(p.accuracy)}</span></div></div><div class="cards"><div class="card"><b>Рождение</b><span class="muted">${fmtDate(p.birth)} · ${esc(p.time||'время не указано')}<br>${esc(p.place||'место не указано')}<br>${esc(p.tz||'часовой пояс не указан')}</span></div><div class="card"><b>Что требуется</b><span class="warning">${esc(c.reason)}</span><br><button class="btn" style="margin-top:10px" onclick="openEdit(state.active)">Дополнить профиль</button></div></div><div class="notice">Расчёт не подменяется догадкой: без исходных данных система ничего не назначает человеку.</div>`;const h=c.hd;return`<div class="heroCard"><div class="label">Human Design · локальный расчёт</div><h2>${esc(p.name)}</h2><div class="chips"><span class="chip good">рассчитано в браузере</span><span class="chip">${esc(precisionLabel(c))}</span><span class="chip">${esc(p.accuracy)}</span></div></div>${hdSummary(c)}${hypothesisCards(h)}${centerSvg(h)}<div class="cards">${channelCards(h)}<div class="card"><b>Определённые центры</b><span class="muted">${h.definedCenters.map(x=>esc(HumanMatrixHD.CENTER_LABELS[x])).join(' · ')||'нет'}</span></div><div class="card"><b>Открытые центры</b><span class="muted">${h.openCenters.map(x=>esc(HumanMatrixHD.CENTER_LABELS[x])).join(' · ')}</span></div></div><div class="notice"><b>Практический слой:</b> трактовки будут формулироваться как гипотезы для наблюдения отдельно от вычисленного BodyGraph.</div>`}
function pairView(){if(state.people.length<2)return'<div class="notice">Добавьте второго человека.</div>';state.pairA=Math.min(state.pairA,state.people.length-1);state.pairB=Math.min(Math.max(state.pairB,1),state.people.length-1);if(state.pairA===state.pairB)state.pairB=(state.pairA+1)%state.people.length;const opts=state.people.map((p,i)=>`<option value="${i}">${esc(p.name)}</option>`).join('');const a=state.people[state.pairA],b=state.people[state.pairB],ca=calcFor(a),cb=calcFor(b);const selectors=`<div class="form"><select id="pairA" onchange="state.pairA=+this.value;renderContent()">${opts}</select><select id="pairB" onchange="state.pairB=+this.value;renderContent()">${opts}</select></div>`;setTimeout(()=>{const aa=document.getElementById('pairA'),bb=document.getElementById('pairB');if(aa)aa.value=state.pairA;if(bb)bb.value=state.pairB},0);if(!ca.ready||!cb.ready)return`<div class="heroCard"><div class="label">Связка</div><h2>${esc(a.name)} × ${esc(b.name)}</h2></div>${selectors}<div class="notice">Для расчётного сравнения обоим участникам нужны дата, время и часовой пояс.</div>`;const r=HumanMatrixHD.compare(ca.hd,cb.hd);const rel=(title,arr)=>`<div class="card"><b>${title} · ${arr.length}</b>${arr.length?`<div class="gateList">${arr.map(x=>`<span class="gate">${x.gates.join('–')}</span>`).join('')}</div>`:'<span class="muted">нет</span>'}</div>`;return`<div class="heroCard"><div class="label">Connection layer</div><h2>${esc(a.name)} × ${esc(b.name)}</h2><p class="muted">Механические связи двух карт — не рейтинг качества отношений.</p></div>${selectors}<div class="cards">${rel('Электромагнитные',r.electromagnetic)}${rel('Companionship',r.companionship)}${rel('Компромиссные',r.compromise)}${rel('Доминирующие',r.dominance)}</div><div class="notice">Следующий слой пары — перевод связей в вопросы для коммуникации и наблюдения без процентов «совместимости».</div>`}
function teamView(){
 const rows=state.people.map(p=>({p,c:calcFor(p)})),ready=rows.filter(x=>x.c.ready),types={},coverage={};
 ready.forEach(x=>{types[x.c.hd.type]=(types[x.c.hd.type]||0)+1;x.c.hd.definedCenters.forEach(c=>coverage[c]=(coverage[c]||0)+1)});
 let pairEdges=0,electro=0;for(let i=0;i<ready.length;i++)for(let j=i+1;j<ready.length;j++){const r=HumanMatrixHD.compare(ready[i].c.hd,ready[j].c.hd);pairEdges++;electro+=r.electromagnetic.length}
 const covered=HumanMatrixHD.CENTERS.filter(c=>coverage[c]),gaps=HumanMatrixHD.CENTERS.filter(c=>!coverage[c]);
 return `<div class="heroCard"><div class="label">Командная матрица</div><h2>${state.people.length} из 5 участников</h2><p class="muted">${ready.length} профилей рассчитаны. Это агрегированный HD/composite-слой, не BG5/Penta.</p></div><div class="matrix" style="margin-top:14px">${rows.map(({p,c},i)=>`<div class="slot"><strong>${i+1}. ${esc(p.name)}</strong><span>${c.ready?`${esc(c.hd.type)} · ${esc(c.hd.profile)}`:'нужны данные'}<br>${esc(p.accuracy)}</span></div>`).join('')}</div><div class="cards"><div class="card"><b>Состав по типам</b><span class="muted">${Object.entries(types).map(([k,v])=>`${esc(k)}: ${v}`).join('<br>')||'нет рассчитанных профилей'}</span></div><div class="card"><b>Покрытие центров</b><span class="muted">${covered.map(c=>`${esc(HumanMatrixHD.CENTER_LABELS[c])} (${coverage[c]})`).join(' · ')||'—'}</span></div><div class="card"><b>Не покрыты ни одним участником</b><span class="muted">${gaps.map(c=>esc(HumanMatrixHD.CENTER_LABELS[c])).join(' · ')||'все центры встречаются хотя бы у одного участника'}</span></div><div class="card"><b>Сеть пар</b><span class="muted">Проверено пар: ${pairEdges}. Электромагнитных дополнений между ними: ${electro}. Это повод исследовать связки, а не рейтинг команды.</span></div></div><div class="notice">BG5/Penta будет отдельным модулем после проверки правил. Сейчас команда показывает только то, что можно прозрачно вывести из индивидуальных карт и парных composite-связей.</div>`
}
function systemsView(){return`<div class="cards"><div class="card"><b class="good">Human Design · работает</b><span class="muted">Локальные активации, ворота, каналы, центры, Type, Strategy, Authority и Profile.</span></div><div class="card"><b>Connection chart · работает</b><span class="muted">Базовая механика пары: electromagnetic, companionship, compromise, dominance.</span></div><div class="card"><b>BG5 / Penta</b><span class="muted">Следующий исследовательский модуль.</span></div><div class="card"><b>Майянские системы</b><span class="muted">В очереди: конкретная традиция + прозрачный алгоритм + источник.</span></div><div class="card"><b>Славянский слой</b><span class="muted">Исторический месяцеслов отдельно от современных реконструкций.</span></div><div class="card"><b class="good">Evidence layer</b><span class="muted">Фактические наблюдения остаются отдельно от трактовок.</span></div></div>`}
function observationsView(){const p=active();if(!p)return'<div class="notice">Добавьте участника.</div>';const notes=p.notes||[];return`<div class="heroCard"><div class="label">Evidence layer</div><h2>Наблюдения: ${esc(p.name)}</h2><p class="muted">Записываем факты, чтобы позже сравнивать их с гипотезами систем.</p></div><div class="form"><input id="obsInput" class="full" placeholder="Например: легче принимает важные решения после паузы"/><button class="btn primary full" onclick="addObservation()">Добавить наблюдение</button></div><div class="cards">${notes.length?notes.map((n,i)=>`<div class="card"><b>Наблюдение ${i+1}</b><span class="muted">${esc(n)}</span></div>`).join(''):'<div class="card"><span class="muted">Пока наблюдений нет.</span></div>'}</div>`}
function renderContent(){renderTabs();const map={person:personView,pair:pairView,team:teamView,systems:systemsView,observations:observationsView};document.getElementById('content').innerHTML=map[state.mode]()}
function render(){renderPeople();renderContent()}
function openForm(){document.getElementById('formWrap').style.display='block'}
function closeForm(){document.getElementById('formWrap').style.display='none';state.editing=null;['name','birth','time','place','tz'].forEach(id=>document.getElementById(id).value='');document.getElementById('accuracy').value='Время точное'}
function openEdit(i){state.editing=i;state.active=i;const p=state.people[i];openForm();name.value=p.name||'';birth.value=p.birth||'';time.value=p.time||'';place.value=p.place||'';tz.value=p.tz||'';accuracy.value=p.accuracy||'Время точное'}
function savePerson(){const data={id:state.editing==null?crypto.randomUUID():state.people[state.editing].id,name:name.value.trim()||'Без имени',birth:birth.value,time:time.value,place:place.value.trim(),tz:tz.value.trim(),accuracy:accuracy.value,notes:state.editing==null?[]:(state.people[state.editing].notes||[])};if(state.editing==null){state.people.push(data);state.active=state.people.length-1}else state.people[state.editing]=data;persist();closeForm();render()}
function removePerson(i){if(!confirm(`Удалить профиль «${state.people[i].name}»?`))return;state.people.splice(i,1);state.active=Math.max(0,Math.min(state.active,state.people.length-1));persist();render()}
function addObservation(){const v=document.getElementById('obsInput').value.trim();if(!v)return;const p=active();p.notes=p.notes||[];p.notes.unshift(v);persist();renderContent()}
document.getElementById('addBtn').onclick=()=>{state.editing=null;openForm()};document.getElementById('saveBtn').onclick=savePerson;document.getElementById('cancelBtn').onclick=closeForm;render();
