/* City lookup sends only the search text, never profile or birth data. */
window.createPlacePicker=function(){
 const input=document.getElementById('place'),zone=document.getElementById('tz'),list=document.getElementById('placeResults'),status=document.getElementById('placeStatus'),manual=document.getElementById('manualZone');
 let timer,controller,revision=0,selected=null,items=[],cursor=-1;
 function hide(){list.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');cursor=-1}
 function cancel(){clearTimeout(timer);controller?.abort();revision++}
 function zoneInfo(){const date=document.getElementById('birth').value,time=document.getElementById('time').value;if(!zone.value){document.getElementById('zoneInfo').textContent='Определится после выбора города.';return}document.getElementById('zoneInfo').textContent=HumanMatrixHD.zoneLabel(date,time,zone.value)}
 function choose(i){const p=items[i];if(!p)return;cancel();selected=p;input.value=p.label;zone.value=p.tz;manual.checked=false;zone.readOnly=true;hide();status.textContent='Место выбрано. Часовой пояс определён автоматически.';zoneInfo()}
 async function search(){cancel();const token=revision,q=input.value.trim();hide();if(q.length<2){status.textContent='Введите минимум 2 буквы названия города.';return}status.textContent='Ищем населённые пункты…';controller=new AbortController();const timeout=setTimeout(()=>controller?.abort(),10000);
 try{const url=new URL('https://geocoding-api.open-meteo.com/v1/search');url.search=new URLSearchParams({name:q,count:'10',language:'ru',format:'json'});const res=await fetch(url,{signal:controller.signal});if(!res.ok)throw new Error('network');const data=await res.json();if(token!==revision)return;if(data.error)throw new Error('api');items=(data.results||[]).filter(p=>{try{return p.name&&p.timezone&&!!new Intl.DateTimeFormat('en',{timeZone:p.timezone})}catch{return false}}).map(p=>({label:[...new Set([p.name,p.admin1,p.country].filter(Boolean))].join(', '),tz:p.timezone,lat:p.latitude,lon:p.longitude,placeId:p.id}));list.replaceChildren();items.forEach((p,i)=>{const el=document.createElement('li');el.id='place-option-'+i;el.role='option';el.textContent=p.label;el.addEventListener('click',()=>choose(i));list.append(el)});list.hidden=!items.length;input.setAttribute('aria-expanded',String(!!items.length));status.textContent=items.length?'Выберите нужный город из списка.':'Город не найден. Попробуйте другое написание или ближайший город с тем же часовым поясом.';
 }catch(e){if(token===revision){hide();status.textContent='Поиск недоступен. Повторите поиск или укажите пояс вручную в дополнительных настройках.'}}finally{clearTimeout(timeout)}}
 input.addEventListener('input',()=>{cancel();selected=null;zone.value='';manual.checked=false;zone.readOnly=true;hide();zoneInfo();status.textContent='Введите название и выберите город из списка.';timer=setTimeout(search,350)});
 input.addEventListener('keydown',e=>{if(e.key==='Escape'){cancel();hide()}if(e.key==='ArrowDown'||e.key==='ArrowUp'){if(list.hidden)return;e.preventDefault();cursor=(cursor+(e.key==='ArrowDown'?1:-1)+items.length)%items.length;Array.from(list.children).forEach((el,i)=>el.setAttribute('aria-selected',String(i===cursor)));input.setAttribute('aria-activedescendant',list.children[cursor].id);list.children[cursor].scrollIntoView({block:'nearest'})}if(e.key==='Enter'&&!list.hidden){e.preventDefault();if(cursor>=0)choose(cursor)}});
 document.getElementById('placeSearch').onclick=search;
 manual.onchange=()=>{cancel();hide();selected=null;zone.readOnly=!manual.checked;zone.value='';zoneInfo();if(manual.checked)zone.focus()};zone.addEventListener('input',zoneInfo);document.getElementById('birth').addEventListener('change',zoneInfo);document.getElementById('time').addEventListener('change',zoneInfo);
 return {reset(p){cancel();hide();items=[];selected=p.place&&p.tz?{label:p.place,tz:p.tz,lat:p.lat,lon:p.lon,placeId:p.placeId}:null;manual.checked=false;zone.readOnly=true;status.textContent=selected?'Сохранённое место. Для изменения выберите город из подсказок.':'Введите название и выберите город из списка.';zoneInfo()},close(){cancel();hide()},value(){if(manual.checked&&input.value.trim()&&zone.value.trim())return {};if(!selected||selected.label!==input.value.trim()||selected.tz!==zone.value)throw new Error('Выберите место рождения из списка — часовой пояс заполнится автоматически.');return {lat:selected.lat,lon:selected.lon,placeId:selected.placeId}}};
};
